#!/usr/bin/env bash

create_branch()
{
    cmd=`git config -l |grep fetch`

    cmd=`echo $cmd | cut -d '.' -f2`
    git fetch $cmd

    remote_branch=$cmd/$1
    git branch $1 $remote_branch
}

create_branch $1